"use strict";

function DummyContext() { }

const contextPrototype = [
  "canvas",
  "globalAlpha",
  "globalCompositeOperation",
  "filter",
  "imageSmoothingEnabled",
  "imageSmoothingQuality",
  "strokeStyle",
  "fillStyle",
  "shadowOffsetX",
  "shadowOffsetY",
  "shadowBlur",
  "shadowColor",
  "lineWidth",
  "lineCap",
  "lineJoin",
  "miterLimit",
  "lineDashOffset",
  "font",
  "textAlign",
  "textBaseline",
  "direction",
  "clip",
  "createImageData",
  "createLinearGradient",
  "createPattern",
  "createRadialGradient",
  "drawFocusIfNeeded",
  "drawImage",
  "fill",
  "fillText",
  "getContextAttributes",
  "getImageData",
  "getLineDash",
  "getTransform",
  "isPointInPath",
  "isPointInStroke",
  "measureText",
  "putImageData",
  "save",
  "scale",
  "setLineDash",
  "setTransform",
  "stroke",
  "strokeText",
  "transform",
  "translate",
  "arc",
  "arcTo",
  "beginPath",
  "bezierCurveTo",
  "clearRect",
  "closePath",
  "ellipse",
  "fillRect",
  "lineTo",
  "moveTo",
  "quadraticCurveTo",
  "rect",
  "resetTransform",
  "restore",
  "rotate",
  "strokeRect"
]

DummyContext.prototype = contextPrototype.reduce((context, key) => ({
  ...context,
  [key]: () => ({})
}), {});

module.exports = DummyContext;
